### ISSUE TITLE
Unable to install version 0.3.0 running pip on Ubuntu 20.04.2

### ISSUE THREAD

**Issue by inversoide** [basiliskus/appman#1]
I have a previous version of appman, and I'm trying to install the new one. I tried using pip uninstall appman and gave me an error.

Then:
pip install appman
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: appman in /usr/local/lib/python3.8/dist-packages (0.1.1)
Requirement already satisfied: click<9.0.0,>=8.0.1 in /home/username/.local/lib/python3.8/site-packages (from appman) (8.0.1)
Requirement already satisfied: pyyaml<6.0.0,>=5.3.1 in /usr/lib/python3/dist-packages (from appman) (5.3.1)

However, when I try to run appman it gives me the following error:
appman add
bash: /home/username/.local/bin/appman: No such file or directory

Any help is appreciated :)

**Comment by inversoide** [comment]
I was able to install it by using the commnad:
sudo python3.9 -m pip install appman

However, when I run it I get the following error: 
appman add
bash: /home/username/.local/bin/appman: No such file or directory

**Comment by basiliskus** [comment]
> I was able to install it by using the commnad:
> sudo python3.9 -m pip install appman
pip should be called without sudo, like this:
`python3.9 -m pip install appman`

But first, try uninstalling the sudo installed package:
`sudo python3.9 -m pip uninstall -y appman`

And then, try installing again:
`python3.9 -m pip install appman`

Hope this helps

**Comment by inversoide** [comment]
Thank yo, worked like a charm!
